### ISSUE TITLE
How to pass config file in lint-action?

### ISSUE THREAD

**Issue by kushthedude** [golangci/golangci-lint-action#26]
**Question**

How do I pass the `.golangci-lint.yml` the configuration file in the following action?

**Comment by bombsimon** [comment]
Put your config named `.golangci.yml` according to the [docs](https://golangci-lint.run/usage/configuration#config-file) in the root of your project and the action will use that. This is because `golangci-lint` will look for config files in all directories from the directory of the first analyzed path up to the root.

If you want to name it something else or store it somewhere else you can use `args: --config=/path/to/.golangci-lint.yml` in your action.

**Comment by kushthedude** [comment]
Thanks @bombsimon , It was not mentioned in the actions readme.

**Comment by emil14** [comment]
> Put your config named .golangci.yml according to the docs in the root of your project

It would be great if we could add this to `README.md` because it's not clear

**Comment by bombsimon** [comment]
It is mentioned [here](https://golangci-lint.run/usage/configuration/#config-file), is there anything that needs to be clearer?

**Comment by emil14** [comment]
> However, maybe we could mention that the action just runs the binary and all docs and configs is the same for the action with a link to these docs?

It would be great! Documentation is never too clear :)
