### ISSUE TITLE
Feature request: allow something to the effect of version: latest

### ISSUE THREAD

**Issue by zmwangx** [golangci/golangci-lint-action#27]
Currently, the version parameter must be set to `vx.y`, but golangci-lint releases minor versions pretty rapidly, so for side projects this means the version used on CI is quickly outdated, or one has to babysit the CI very frequently. In fact, the README example is already out of date.

IMO CI is mostly a set-and-forget thing for most people's side projects, and I can't really see the benefit the pinning golangci-lint to a minor release, so this restriction seems to do a disservice.

Would it be possible to support `version: latest` or `version: ^v1.27` or something to that effect?

**Comment by jirfag** [comment]
Hi,
I'm worried about cases when `golangci-lint gets updated and all CI builds start failing because of newly added linters (we add them and update current linters in minor releases, see our [versioning policy](https://golangci-lint.run/usage/install/#versioning-policy)).

Ideal solution would be a dependabot-like updating with a pull request. Also, we can find a way to show warning about outdated `golangci-lint` version.

**Comment by zmwangx** [comment]
> golangci-lint gets updated and all CI builds start failing because of newly added linters

IMHO a choice would be nice.

If my policy is “this project should pass golangci-lint”, not “should pass golangci-lint vx.y”, I do want to be alerted to the slightly unlikely scenario of code falling out of compliance with newly added default-on linters. Having it automatically occur with the latest version is certainly better than having to update the version all the time, even if there’s a dependabot submitting PRs (still requires some effort, and pollutes commit history).

Other people can choose of pin versions, of course, especially on highly active projects.
