### ISSUE TITLE
Add option to restore cache only (for PRs)

### ISSUE THREAD

**Issue by ForsakenHarmony** [golangci/golangci-lint-action#641]
### Your feature request related to a problem? Please describe.

GitHub has a 10 GB limit for actions caches, this action alone is using 130 MB for us, it would be nice to not also get another 130 MB for each opened PR.

### Describe the solution you'd like.

Add a `save-cache` option to be able to still restore cache (e.g. from `main`), but not save a new cache entry

### Additional context.

https://github.com/actions/toolkit/issues/1308
https://github.com/Swatinem/rust-cache/issues/95 (has a `save-if` option https://github.com/Swatinem/rust-cache#example-usage)

**Comment by bombsimon** [comment]
Is the option `skip-cache` not working for you? From the docs:

```
# Optional: if set to true then the all caching functionality will be complete disabled,
#           takes precedence over all other caching options.
# skip-cache: true
```

**Comment by ForsakenHarmony** [comment]
@bombsimon I want to still restore the cache, but not save it

**Comment by krhubert** [comment]
This option would be great in order to reduce total cache size (on GH it's limited to 10GB). 

Golang cache can take between 300-500 MB easily and because of that repo can quickly hit cache storage limit. One of possible [solution](https://stackoverflow.com/questions/69365200/github-actions-how-to-cache-dependencies-between-workflow-runs-of-different-bra) to this problem is to save cache only on the main branch and use read-only mode for non main branches.
